# Translations template for ironic.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ironic project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ironic 2014.2.dev98.g8576905\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-22 06:09+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ironic/api/middleware/parsable_error.py:82
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ironic/common/exception.py:79
msgid "Exception in string format operation"
msgstr ""

#: ironic/common/images.py:132
#, python-format
msgid "vfat image creation failed. Error: %s"
msgstr ""

#: ironic/common/images.py:200
msgid "Creating the filesystem root failed."
msgstr ""

#: ironic/common/images.py:214
msgid "Creating ISO image failed."
msgstr ""

#: ironic/common/service.py:88
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: ironic/common/service.py:93
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: ironic/common/utils.py:415
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: ironic/common/utils.py:448
#, python-format
msgid "Failed to make file system. File system %s is not supported."
msgstr ""

#: ironic/common/utils.py:452
#, python-format
msgid "Failed to create a file system in %(path)s. Error: %(error)s"
msgstr ""

#: ironic/common/glance_service/base_image_service.py:128
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""

#: ironic/conductor/manager.py:705
#, python-format
msgid "Failed to change power state of node %(node)s to '%(state)s'."
msgstr ""

#: ironic/dhcp/neutron.py:114
#, python-format
msgid "Failed to update Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:128
#, python-format
msgid "Failed to update MAC address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:190
#, python-format
msgid "Failed to Get IP address on Neutron port %s."
msgstr ""

#: ironic/dhcp/neutron.py:206
#, python-format
msgid "Neutron returned invalid IPv4 address %s."
msgstr ""

#: ironic/dhcp/neutron.py:210
#, python-format
msgid "No IP address assigned to Neutron port %s."
msgstr ""

#: ironic/drivers/modules/agent.py:380
#, python-format
msgid "vendor_passthru failed with method %s"
msgstr ""

#: ironic/drivers/modules/agent.py:417
#, python-format
msgid "Async exception for %(node)s: %(msg)s"
msgstr ""

#: ironic/drivers/modules/agent.py:584
#, python-format
msgid "Could not find matching node for the provided MACs %s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:236
#, python-format
msgid ""
"Failed to erase beginning of disk for node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:248
#, python-format
msgid ""
"Failed to get disk block count for node %(node)s. Command: %(command)s. "
"Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:261
#, python-format
msgid ""
"Failed to erase the end of the disk on node %(node)s. Command: "
"%(command)s. Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:326
msgid "Failed to detect root device UUID."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:364
#: ironic/drivers/modules/deploy_utils.py:370
#, python-format
msgid "Deploy to address %s failed."
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:365
#, python-format
msgid "Command: %s"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:366
#, python-format
msgid "StdOut: %r"
msgstr ""

#: ironic/drivers/modules/deploy_utils.py:367
#, python-format
msgid "StdErr: %r"
msgstr ""

#: ironic/drivers/modules/ipminative.py:263
#, python-format
msgid ""
"IPMI get sensor data failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:414
#, python-format
msgid ""
"IPMI set boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipminative.py:449
#, python-format
msgid ""
"IPMI get boot device failed for node %(node_id)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ipmitool.py:413
#, python-format
msgid ""
"IPMI power %(state)s timed out after %(tries)s retries on node "
"%(node_id)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:818
#, python-format
msgid "IPMI \"raw bytes\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ipmitool.py:852
#, python-format
msgid "IPMI \"bmc reset\" failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:293
#, python-format
msgid "Error returned from deploy ramdisk: %s"
msgstr ""

#: ironic/drivers/modules/iscsi_deploy.py:306 ironic/drivers/modules/pxe.py:485
#: ironic/drivers/modules/ilo/deploy.py:533
#, python-format
msgid "Deploy failed for instance %(instance)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/pxe.py:289
msgid "UEFI boot mode is not supported with iPXE boot enabled."
msgstr ""

#: ironic/drivers/modules/pxe.py:462 ironic/drivers/modules/ilo/deploy.py:502
#, python-format
msgid "Node %s is not waiting to be deployed."
msgstr ""

#: ironic/drivers/modules/seamicro.py:167
#, python-format
msgid "SeaMicro client exception %(msg)s for node %(uuid)s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:451
#: ironic/drivers/modules/seamicro.py:487
#, python-format
msgid "SeaMicro client exception: %s"
msgstr ""

#: ironic/drivers/modules/seamicro.py:550
#, python-format
msgid ""
"Seamicro set boot device failed for node %(node)s with the following "
"error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ssh.py:368
#, python-format
msgid "Node \"%(host)s\" with MAC address %(mac)s not found."
msgstr ""

#: ironic/drivers/modules/ssh.py:652
#, python-format
msgid ""
"Failed to set boot device for node %(node)s, virt_type %(vtype)s does not"
" support this operation"
msgstr ""

#: ironic/drivers/modules/drac/management.py:77
#, python-format
msgid ""
"DRAC driver failed to get next boot mode for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:150
#, python-format
msgid ""
"DRAC driver failed to list the configuration jobs for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:234
#, python-format
msgid ""
"DRAC driver failed to set the boot device for node %(node_uuid)s. Can't "
"find the ID for the %(device)s type. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/management.py:301
#, python-format
msgid ""
"DRAC driver failed to get the current boot device for node %(node_uuid)s."
" Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:60
#, python-format
msgid ""
"DRAC driver failed to get power state for node %(node_uuid)s. Reason: "
"%(error)s."
msgstr ""

#: ironic/drivers/modules/drac/power.py:89
#: ironic/drivers/modules/drac/power.py:101
#, python-format
msgid ""
"DRAC driver failed to set power state for node %(node_uuid)s to "
"%(target_power_state)s. Reason: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/common.py:401
#, python-format
msgid "Error while deleting %(object_name)s from %(container)s. Error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/common.py:411
#, python-format
msgid ""
"Error while ejecting virtual media %(device)s from node %(uuid)s. Error: "
"%(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:100
#, python-format
msgid ""
"Unable to find boot_iso in Glance, required to deploy node %(node)s in "
"UEFI boot mode."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:110
#, python-format
msgid ""
"Unable to find 'kernel_id' and 'ramdisk_id' in Glance image %(image)s for"
" generating boot ISO for %(node)s"
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:151
#, python-format
msgid "Failed to clean up boot ISO for %(node)s.Error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/deploy.py:515
#, python-format
msgid "Cannot get boot ISO for node %s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:83
#, python-format
msgid "iLO get_power_state failed for node %(node_id)s with error: %(error)s."
msgstr ""

#: ironic/drivers/modules/ilo/power.py:155
#, python-format
msgid ""
"iLO set_power_state failed to set state to %(tstate)s  for node "
"%(node_id)s with error: %(error)s"
msgstr ""

#: ironic/drivers/modules/ilo/power.py:168
#, python-format
msgid "iLO failed to change state to %(tstate)s within %(timeout)s sec"
msgstr ""

#: ironic/objects/base.py:71
#, python-format
msgid "Error setting %(attr)s"
msgstr ""

#: ironic/objects/base.py:222
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr ""

#: ironic/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: ironic/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: ironic/openstack/common/lockutils.py:119
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: ironic/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: ironic/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: ironic/openstack/common/periodic_task.py:202
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: ironic/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr ""

#: ironic/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr ""

#: ironic/tests/db/sqlalchemy/test_migrations.py:172
#, python-format
msgid "Failed to migrate to version %(version)s on engine %(engine)s"
msgstr ""

